spring:
    application:
      name: SnookerScore

    datasource:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost/snooker?useSSL=false
          username: root
          password: lera77

    jpa:
      hibernate:
        ddl-auto: none

server:
    port: 8080
    context-path: /snook

---
spring:
  profiles: production

  datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/snooker?useSSL=false
        username: root
        password: 123mudar


---

spring:
  profiles: development

  datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/snooker?useSSL=false
        username: root
        password: lera77


#logging:
#  level:
#    org:
#      springframework:
#        web: DEBUG
